/**
 * Injected into the Storybook preview document (app/iframe.html) by tools/pack.mjs.
 *
 * Two jobs:
 *  1. register the service worker at the site root, so the thing installs and runs offline;
 *  2. draw a launcher for switching between the scheduling screens, since an installed PWA
 *     has no address bar to type a story id into.
 *
 * Screens come from `window.__SPIKE_SCREENS` (root screens.js, generated by pack.mjs).
 * Switching screens is a same-document navigation — it stays inside the standalone window.
 */
;(() => {
  const params = new URLSearchParams(location.search)
  if (params.get('chrome') === '0') return registerWorker()

  const screens = window.__SPIKE_SCREENS ?? []
  const current = params.get('id')
  const flat = screens.flatMap((g) => g.items)
  const currentLabel = flat.find((s) => s.id === current)?.label ?? 'Kies scherm'

  const fab = document.createElement('button')
  fab.type = 'button'
  fab.className = 'spike-fab'
  fab.setAttribute('aria-haspopup', 'dialog')
  fab.textContent = currentLabel
  document.body.appendChild(fab)

  let backdrop = null
  let sheet = null

  function close() {
    backdrop?.remove()
    sheet?.remove()
    backdrop = sheet = null
    fab.dataset.open = 'false'
  }

  function go(id) {
    const next = new URLSearchParams(location.search)
    next.set('id', id)
    next.set('viewMode', 'story')
    location.search = next.toString()
  }

  function open() {
    fab.dataset.open = 'true'
    backdrop = document.createElement('div')
    backdrop.className = 'spike-backdrop'
    backdrop.addEventListener('click', close)

    sheet = document.createElement('div')
    sheet.className = 'spike-sheet'
    sheet.setAttribute('role', 'dialog')
    sheet.setAttribute('aria-label', 'Schermen')
    sheet.innerHTML = '<div class="spike-grip"></div>'

    for (const group of screens) {
      const heading = document.createElement('div')
      heading.className = 'spike-group'
      heading.textContent = group.group
      sheet.appendChild(heading)
      for (const item of group.items) {
        const button = document.createElement('button')
        button.type = 'button'
        button.className = 'spike-item'
        if (item.id === current) button.setAttribute('aria-current', 'true')
        button.innerHTML = `<span>${item.label}</span><span class="note">${item.note ?? ''}</span>`
        button.addEventListener('click', () => go(item.id))
        sheet.appendChild(button)
      }
    }

    const foot = document.createElement('div')
    foot.className = 'spike-foot'
    foot.textContent =
      'Spike op vaste testdata (geen patiëntgegevens, geen server). Voeg toe aan beginscherm voor de volledige app-modus; ?chrome=0 verbergt deze knop.'
    sheet.appendChild(foot)

    document.body.append(backdrop, sheet)
  }

  fab.addEventListener('click', () => (sheet ? close() : open()))
  registerWorker()

  function registerWorker() {
    if (!('serviceWorker' in navigator)) return
    addEventListener('load', () => {
      navigator.serviceWorker.register(new URL('../sw.js', location.href)).catch(() => {})
    })
  }
})()
